Repository GregoireHebert/docusign-bundle, pull requests merged in 2019-11, with the labels that each got.

#21 Add JWT Grant authentication
  README.md
  composer.json
  src/DependencyInjection/Compiler/EnvelopeBuilderPass.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/DocusignExtension.php
  src/EnvelopeBuilder.php
  src/Grant/GrantInterface.php
  src/Grant/JwtGrant.php
  src/Resources/config/services.xml
  tests/DependencyInjection/Compiler/EnvelopeBuilderPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/DocusignExtensionTest.php
  tests/EnvelopeBuilderTest.php
  tests/config/docusign.yml
Labels: bug, enhancement

#39 Add signature mode and revamp EnvelopeBuilder
  README.md
  composer.json
  src/Controller/Sign.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/DocusignExtension.php
  src/EnvelopeBuilder.php
  src/EnvelopeBuilderInterface.php
  src/EnvelopeCreator/CreateDocument.php
  src/EnvelopeCreator/CreateRecipient.php
  src/EnvelopeCreator/DefineEnvelope.php
  src/EnvelopeCreator/EnvelopeBuilderCallableInterface.php
  src/EnvelopeCreator/EnvelopeCreator.php
  src/EnvelopeCreator/EnvelopeCreatorInterface.php
  src/EnvelopeCreator/SendEnvelope.php
  src/Events/PreSignEvent.php
  src/Utils/CallbackRouteGenerator.php
  tests/BundleInitializationTest.php
  tests/Controller/CallbackTest.php
  tests/Controller/SignTest.php
  tests/Controller/WebhookTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/DocusignExtensionTest.php
  tests/EnvelopeBuilderTest.php
  tests/EnvelopeCreator/CreateDocumentTest.php
  tests/EnvelopeCreator/CreateRecipientTest.php
  tests/EnvelopeCreator/DefineEnvelopeTest.php
  tests/EnvelopeCreator/EnvelopeCreatorTest.php
  tests/EnvelopeCreator/SendEnvelopeTest.php
  tests/config/docusign.yml
Labels: enhancement

#47 Update issue and feature templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#46 Contributing
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/FUNDING.yml
Labels: documentation

#51 Clean for Symfony < 4.0
  .github/workflows/ci.yml
  composer.json
  phpstan.neon.lowest.dist
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/DocusignExtension.php
  src/Grant/JwtGrant.php
  src/Resources/config/services.xml
  tests/DependencyInjection/Compiler/EnvelopeBuilderPassTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/DocusignExtensionTest.php
  tests/config/docusign.yml
Labels: bug

#43 update doc
  README.md
  composer.json
  doc/assets/add_integration_key.png
  doc/assets/add_redirect_uri.png
  doc/assets/add_rsa_key.png
  doc/assets/copy_private_rsa_key.png
  doc/assets/integration_key.png
  doc/assets/menu_api_and_keys.png
  doc/assets/user_guid.png
  doc/configure-docusign.md
  doc/configure-the-bundle.md
  doc/customize-the-bundle.md
  doc/events.md
  doc/installation.md
  doc/usage.md
  doc/use-flysystem-bundle.md
Labels: documentation, enhancement

#45 Add translation
  composer.json
  src/Controller/Callback.php
  src/DependencyInjection/Compiler/PluginCompilerPass.php
  src/DependencyInjection/Compiler/TranslationCompilerPass.php
  src/DependencyInjection/DocusignExtension.php
  src/DocusignBundle.php
  src/EnvelopeCreator/DefineEnvelope.php
  src/Resources/translations/docusign_bundle.de.xlf
  src/Resources/translations/docusign_bundle.es.xlf
  src/Resources/translations/docusign_bundle.fr.xlf
  src/Resources/translations/docusign_bundle.it.xlf
  src/Resources/translations/docusign_bundle.nl.xlf
  src/Resources/translations/docusign_bundle.pl.xlf
  src/Resources/translations/docusign_bundle.pt.xlf
  src/Resources/translations/docusign_bundle.ru.xlf
  src/Translator/TranslatorAwareInterface.php
  src/Translator/TranslatorAwareTrait.php
  tests/Controller/CallbackTest.php
  tests/DependencyInjection/DocusignExtensionTest.php
  tests/EnvelopeCreator/CreateDocumentTest.php
  tests/EnvelopeCreator/CreateRecipientTest.php
  tests/EnvelopeCreator/DefineEnvelopeTest.php
  tests/EnvelopeCreator/SendEnvelopeTest.php
Labels: enhancement

#49 Add Traceable behaviour
  src/DependencyInjection/DocusignExtension.php
  src/EnvelopeCreator/TraceableEnvelopeBuilderCallable.php
  src/EnvelopeCreator/TraceableEnvelopeBuilderCallableInterface.php
  tests/DependencyInjection/DocusignExtensionTest.php
Labels: enhancement

#56 BUG: Fix webhookParameters/callbackParameters names
  src/EnvelopeBuilder.php
  src/EnvelopeBuilderInterface.php
Labels: bug

#57 fix documentation
  doc/configure-docusign.md
  doc/configure-the-bundle.md
Labels: bug, documentation

#59 Move config check
  src/DependencyInjection/Configuration.php
  src/EnvelopeBuilder.php
  src/EnvelopeBuilderInterface.php
  src/EnvelopeCreator/SendEnvelope.php
  src/Exception/ConfigurationException.php
  tests/DependencyInjection/DocusignExtensionTest.php
  tests/EnvelopeBuilderTest.php
  tests/EnvelopeCreator/CreateRecipientTest.php
  tests/EnvelopeCreator/SendEnvelopeTest.php
Labels: bug
